# Generated by Django 5.2.5 on 2025-08-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=20)),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnail/')),
            ],
        ),
    ]
