# Generated by Django 5.2.5 on 2025-08-07 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoProcessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('phone_number', models.CharField(unique=True)),
                ('username', models.CharField(max_length=225, unique=True)),
                ('password', models.CharField(max_length=225)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user_picture/')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='videoentity',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VideoProcessing.userentity'),
            preserve_default=False,
        ),
    ]
