# Generated by Django 5.2.5 on 2025-08-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoProcessing', '0003_userentity_groups_userentity_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoentity',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
