# Generated by Django 5.2.5 on 2025-08-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoProcessing', '0004_alter_videoentity_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoentity',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/'),
        ),
    ]
